### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by codediy** [vermiceli/nes-contra-us#1]
![image](https://user-images.githubusercontent.com/20250924/235094267-44c7e194-71cf-4331-8be4-459cec7a778f.png)

**Comment by vermiceli** [comment]
Hi @codediy, I removed the link you provided since that links to a rom, which is property of Konami.  Which build script are you using: .bat, ps1, or .sh?  Do you have the full output logs?  Do you have any .bin files in the `assets/audio_data` and `assets/graphic_data folders`?

**Comment by vermiceli** [comment]
I noticed an issue in the PowerShell build script if you were using PowerShell version less than 7.2.  I've corrected this so the script works regardless of whether you are using PowerShell (< 7.2) or PowerShell Core (> 7.2).  Please let me know if this resolved the issue for you.

**Comment by codediy** [comment]
![image](https://user-images.githubusercontent.com/20250924/235295664-c492fd3f-626d-4e63-b9fd-01f33e85b07c.png)

Run-time error input exceeded the end of the file

**Comment by codediy** [comment]
![image](https://user-images.githubusercontent.com/20250924/235295775-145a6194-e85b-43f8-81f3-701474c3fb43.png)

**Comment by codediy** [comment]
![image](https://user-images.githubusercontent.com/20250924/235295912-5a13a5a1-267b-4466-b703-18d6daec2330.png)

**Comment by vermiceli** [comment]
Hi @codediy, can you confirm that you haven't modified `assets.txt`?  Also, have you tried the powershell version of the build script (`build.ps1`)? You have powershell on your computer.  Open powershell and try to run `.\build.ps1` and let me know if that overcomes your problem.

I don't see anything obviously wrong, but the powershell script will confirm that your `baserom.nes` is exactly right before continuing. I wonder if your rom has an issue.

**Comment by codediy** [comment]
![image](https://user-images.githubusercontent.com/20250924/235311552-8a33b402-b775-4f1b-92bf-87d8b3532a31.png)
![image](https://user-images.githubusercontent.com/20250924/235311577-275f357f-e77d-4f78-adbd-1cb57dea02a0.png)
the img-2 test pass , nes is ok. but ps script `Get-Content .\baserom.nes -AsByteStream` error for img-1

**Comment by codediy** [comment]
![image](https://user-images.githubusercontent.com/20250924/235311685-77bdab1a-29bc-4deb-a977-33745814d329.png)
the assets.txt from this line read data error

**Comment by codediy** [comment]
![image](https://user-images.githubusercontent.com/20250924/235312029-1b70cc01-6134-4f61-87b5-d85a230d5fa6.png)
![image](https://user-images.githubusercontent.com/20250924/235312042-d418a831-206e-40d4-b003-1697abef3e80.png)

when skip byte > 10 0000 ,read fail.

**Comment by codediy** [comment]
[log.txt](https://github.com/vermiceli/nes-contra-us/files/11359588/log.txt)

**Comment by vermiceli** [comment]
HI @codediy, there was an update to the `.build.ps1` script about 20 hours ago.  Could you ensure you have the latest version of the `build.ps1`? The script was updated to work with older versions of PowerShell.  That should resolve the "Get-Content : 找不到与参数名称“AsByteStream”匹配的参数。" error you are getting.

After getting the most recent `build.ps1`, if you are still having errors, try
1.  Run PowerShell as administrator/admin
2. Run `Set-ExecutionPolicy RemoteSigned` to allow certain permissions

I hope this helps. Thanks for including the log file. That was very helpful for me.

**Comment by codediy** [comment]
thank for you help. i got the nes .
![image](https://user-images.githubusercontent.com/20250924/235336982-6454c5c1-d1e8-4141-a85d-9119fd2d01dc.png)
