### ISSUE TITLE
Missing info in readme

### ISSUE THREAD

**Issue by CyberTacoX** [vermiceli/nes-contra-us#2]
In the readme, you wrote: "I first became interested in this project after watching the [Summoning Salt](https://www.youtube.com/channel/UCtUbO6rBht0daVIOGML3c8w) video [The History of Contra World Records](https://www.youtube.com/watch?v=GgOE64kgjjo). In the video starting at 35m 19s, there was a section where a speedrunner named dk28 died in the middle of level 1, and was advanced to level 2 for their next life. The video explains that there still isn't a known explanation as to why this happened."

Well, since that got all of this awesomeness started.... did you find the answer?

**Comment by vermiceli** [comment]
Good callout. I've updated the readme to add that I did not identify the cause of the level skip and that it's still up in the air as to whether it's a software glitch or a hardware bug.  Let's hope that someone is interested and can utilize this code to discover the glitch.
