### ISSUE TITLE
Typo: Graphics Documentation.md

### ISSUE THREAD

**Issue by eightbithero** [vermiceli/nes-contra-us#5]
https://github.com/vermiceli/nes-contra-us/blob/main/docs/Graphics%20Documentation.md

In section about compression 

Below is an example of un-compressed graphics data
```
#$00 #$00 #$00 #00 #$00 #$00 #$0e #$1f #$07 #$04 #$c0
```

When compressed, it becomes

Was
```
#$06 #$00 #$85 #$0e #$1f #$07 #$0f #$c0 #$ff
```

Should be
```
#$06 #$00 #$85 #$0e #$1f #$07 #$04 #$c0 #$ff
```

**Comment by vermiceli** [comment]
Thank you, I've corrected the text.
