### ISSUE TITLE
Contra Randomizer

### ISSUE THREAD

**Issue by sharmashivanand** [vermiceli/nes-contra-us#6]
Is it possible to randomise the level-data in contra? This means every gameplay would be unique.

**Comment by vermiceli** [comment]
Hi @sharmashivanand, modifying _Contra_ is something that is outside of the scope of this project. This project exists to document and preserve the technical implementation of the game.

Modifications are typically referred to as ROM hacks and there are sites and communities for that with https://www.romhacking.net/games/137/ being one of them.  There you can find level editors, and modifications that others have contributed.
